export const SESSIONS_LIST_REQUEST = 'SESSIONS_LIST_REQUEST'
export const SESSIONS_LIST_SUCCESS = 'SESSIONS_LIST_SUCCESS'
export const SESSIONS_LIST_FAIL = 'SESSIONS_LIST_FAIL'

export const SESSIONS_TITLES_REQUEST = 'SESSIONS_TITLES_REQUEST'
export const SESSIONS_TITLES_SUCCESS = 'SESSIONS_TITLES_SUCCESS'
export const SESSIONS_TITLES_FAIL = 'SESSIONS_TITLES_FAIL'

export const SESSION_DETAILS_REQUEST = 'SESSION_DETAILS_REQUEST'
export const SESSION_DETAILS_SUCCESS = 'SESSION_DETAILS_SUCCESS'
export const SESSION_DETAILS_FAIL = 'SESSION_DETAILS_FAIL'
export const SESSION_DETAILS_RESET = 'SESSION_RESET'

export const SESSION_CREATE_REQUEST = 'SESSION_CREATE_REQUEST'
export const SESSION_CREATE_SUCCESS = 'SESSION_CREATE_SUCCESS'
export const SESSION_CREATE_FAIL = 'SESSION_CREATE_FAIL'
export const SESSION_CREATE_RESET = 'SESSION_CREATE_RESET'

export const SESSION_UPDATE_REQUEST = 'SESSION_UPDATE_REQUEST'
export const SESSION_UPDATE_SUCCESS = 'SESSION_UPDATE_SUCCESS'
export const SESSION_UPDATE_FAIL = 'SESSION_UPDATE_FAIL'
export const SESSION_UPDATE_RESET = 'SESSION_UPDATE_RESET'