export const SPECIALIST_LIST_REQUEST = 'SPECIALIST_LIST_REQUEST'
export const SPECIALIST_LIST_SUCCESS = 'SPECIALIST_LIST_SUCCESS'
export const SPECIALIST_LIST_FAIL = 'SPECIALIST_LIST_FAIL'

export const SPECIALIST_DETAILS_REQUEST = 'SPECIALIST_DETAILS_REQUEST'
export const SPECIALIST_DETAILS_SUCCESS = 'SPECIALIST_DETAILS_SUCCESS'
export const SPECIALIST_DETAILS_FAIL = 'SPECIALIST_DETAILS_FAIL'
export const SPECIALIST_DETAILS_RESET = 'SPECIALIST_DETAILS_RESET'

export const SPECIALIST_IMAGES_REQUEST = 'SPECIALIST_IMAGES_REQUEST'
export const SPECIALIST_IMAGES_SUCCESS = 'SPECIALIST_IMAGES_SUCCESS'
export const SPECIALIST_IMAGES_FAIL = 'SPECIALIST_IMAGES_FAIL'

export const SPECIALISTS_NAMES_REQUEST = 'SPECIALISTS_NAMES_REQUEST'
export const SPECIALISTS_NAMES_SUCCESS = 'SPECIALISTS_NAMES_SUCCESS'
export const SPECIALISTS_NAMES_FAIL = 'SPECIALISTS_NAMES_FAIL'
export const SPECIALISTS_NAMES_RESET = 'SPECIALISTS_NAMES_RESET'

export const SPECIALIST_CREATE_REQUEST = 'SPECIALIST_CREATE_REQUEST'
export const SPECIALIST_CREATE_SUCCESS = 'SPECIALIST_CREATE_SUCCESS'
export const SPECIALIST_CREATE_FAIL = 'SPECIALIST_CREATE_FAIL'
export const SPECIALIST_CREATE_RESET = 'SPECIALIST_CREATE_RESET'

export const SPECIALIST_UPDATE_REQUEST = 'SPECIALIST_UPDATE_REQUEST'
export const SPECIALIST_UPDATE_SUCCESS = 'SPECIALIST_UPDATE_SUCCESS'
export const SPECIALIST_UPDATE_FAIL = 'SPECIALIST_UPDATE_FAIL'
export const SPECIALIST_UPDATE_RESET = 'SPECIALIST_UPDATE_RESET'